servers:
  - id: 10001
    type: 0
    useGateMode: true
    addr: 0.0.0.0:8010
    httpAddr: 0.0.0.0:8090
    pprofAddr: :6060
  - id: 1001
    type: 1
    useGateMode: false
    # addr: 127.0.0.1:8011
    addr: 0.0.0.0:8010
    httpAddr: 0.0.0.0:8091
    pprofAddr: :6061
